simple-generator: 
  database-url: jdbc:mysql://192.168.0.202:3306/simple_generator_demo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
  database-username: root
  database-password: secton!!
  projectPath: D:\EclipseWorkSpace\test
  author: zhanglanbin
  groupPropertiesList: 
    - group-name: user
      group-table-name: 
        - "sys_user"
        - "sys_user_info"
    - group-name: system
      group-table-name: 
        - "sys_role"
        - "sys_user_role"
    - group-name: tree
      group-table-name: 
        - "sys_config"






